import { useMemo, useState } from 'react';
import { ArrowLeft, Globe2, MapPin, RotateCcw } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useLeads } from '../context/LeadContext';

export default function LeadGlobe() {
  const { leads } = useLeads();
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const locatedLeads = useMemo(() => leads.filter((lead: any) => Number.isFinite(lead.latitude) && Number.isFinite(lead.longitude)), [leads]);
  const selected = leads.find((lead: any) => lead.id === selectedId);

  return <div className="space-y-8 animate-in fade-in duration-700">
    <header className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[var(--accent)]">Scout map</p><h1 className="mt-2 text-3xl font-black text-[var(--text-primary)]">Lead Globe</h1><p className="mt-2 max-w-2xl text-[var(--text-secondary)]">Explore saved business locations. Tap a pin to zoom into its region and inspect the lead.</p></div><div className="neo-card flex items-center gap-3 px-4 py-3 text-sm text-[var(--text-secondary)]"><Globe2 size={18} className="text-[var(--accent)]" />{locatedLeads.length} mapped leads</div></header>
    <section className="neo-card overflow-hidden p-4 md:p-8"><div className="relative mx-auto aspect-square max-w-3xl overflow-hidden rounded-full border border-[var(--accent)]/30 bg-[radial-gradient(circle_at_35%_30%,rgba(255,255,255,.18),transparent_34%),radial-gradient(circle_at_50%_50%,var(--accent),var(--bg)_68%)] shadow-[0_0_90px_rgba(255,122,0,.18),inset_-35px_-20px_80px_rgba(0,0,0,.32)] transition-transform duration-700" style={{ transform: selected ? 'scale(1.08)' : 'scale(1)' }}><div className="pointer-events-none absolute inset-[-12%] rounded-full border border-white/15" /><div className="pointer-events-none absolute inset-[8%] rounded-full border border-white/10" style={{ transform: 'rotate(25deg) scaleX(.32)' }} /><div className="pointer-events-none absolute inset-[8%] rounded-full border border-white/10" style={{ transform: 'rotate(-25deg) scaleX(.32)' }} /><div className="pointer-events-none absolute inset-0 opacity-20" style={{ backgroundImage: 'linear-gradient(90deg, transparent 49%, currentColor 50%, transparent 51%), linear-gradient(0deg, transparent 49%, currentColor 50%, transparent 51%)', backgroundSize: '25% 25%' }} />{locatedLeads.map((lead: any) => <button key={lead.id} type="button" aria-label={`Open ${lead.businessName}`} onClick={() => setSelectedId(lead.id)} className={`absolute z-10 -translate-x-1/2 -translate-y-1/2 rounded-full p-2 transition-all ${selectedId === lead.id ? 'scale-150 bg-[var(--accent)] text-white shadow-[0_0_24px_var(--accent)]' : 'bg-white text-[var(--accent)] shadow-lg hover:scale-125'}`} style={{ left: `${((lead.longitude + 180) / 360) * 100}%`, top: `${((90 - lead.latitude) / 180) * 100}%` }}><MapPin size={14} fill="currentColor" /></button>)}</div><div className="mt-5 flex items-center justify-between gap-3 text-xs text-[var(--text-secondary)]"><span>{locatedLeads.length ? 'Tap a pin to zoom and inspect it.' : 'No saved leads have coordinates yet. Save new Lead Finder results to place pins.'}</span><button type="button" onClick={() => setSelectedId(null)} className="btn-neumorph inline-flex items-center gap-2 px-3 py-2"><RotateCcw size={13} /> Reset view</button></div></section>
    {selected && <section className="neo-card flex flex-col gap-4 p-5 md:flex-row md:items-center md:justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-[var(--accent)]">Selected lead</p><h2 className="mt-1 text-xl font-bold text-[var(--text-primary)]">{selected.businessName}</h2><p className="mt-1 text-sm text-[var(--text-secondary)]">{selected.city} - {selected.category}</p></div><Link to={`/leads/${selected.id}`} className="btn-neumorph-primary inline-flex items-center justify-center gap-2 px-4 py-2"><ArrowLeft size={14} /> View lead</Link></section>}
  </div>;
}
